// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc6071.BCCFRCROBOT.commands;

import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

import org.usfirst.frc6071.BCCFRCROBOT.*;

/**
 *
 */
public class AutonomousCommand extends Command {
	
	// Quick set for time based movements in Auton
	
	public int autonType = 0;
	///		Autonomous Types.
	/// 0: Go Straight
	///	1: Attempt Gear Placement !!! UNFINISHED !!!
	///	

	
	
	private Timer myTimer;
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public AutonomousCommand() {

    }

    // Called just before this Command runs the first time
    protected void initialize() {
    	
    	
    	
    	if (SmartDashboard.getBoolean("DB/Button 1",false)){
    		// Set an int to changethe thingy.
    	}
    	
    	
    	//org.usfirst.frc6071.BCCFRCROBOT.subsystems.autonDrive.clawStation(armTime);
    	//oredg.usfirst.frc6071.BCCFRCROBOT.subsystems.auonDrive.drive(driveTime);
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	
    	org.usfirst.frc6071.BCCFRCROBOT.subsystems.autonDrive.drive(.17);
   
    }
    
    /*else if  (autonType == 1) {
    	System.out.println("Auton 1: Gear Placement Running!");
    	if (myTimer.get() < 2.0){ // First movement. Should move bot forward and be ready to turn.
    		org.usfirst.frc6071.BCCFRCROBOT.subsystems.autonDrive.drive(0);

    	}
    	else if(myTimer.get() < 4.0){ // Turn robot torwards  gearposts.
    		org.usfirst.frc6071.BCCFRCROBOT.subsystems.autonDrive.drive(.3);

    		
    	}
    	else if (myTimer.get() < 6.0){ // Move robot forward and place post on set.
    		org.usfirst.frc6071.BCCFRCROBOT.subsystems.autonDrive.drive(.5);

    	}
    	
    	
    }
    */
    

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    protected void end() {
    	org.usfirst.frc6071.BCCFRCROBOT.subsystems.autonDrive.drive(0);
    }
    //

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}
