// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc6071.BCCFRCROBOT.commands;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc6071.BCCFRCROBOT.Robot;

/**
 *
 */
public class JoystickValues extends Command {

   
    public JoystickValues() {

  
        requires(Robot.driveTrain);


    }

    //**These are the autogenerated sections of code that allow for the students to place the code before the command, during the command, or after the command 
    
    // Called just before this Command runs the first time
    protected void initialize() {
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    
    // **Pulls the raw data from the port of choice on the controller Left-Y-axis=1 Right-Y-axis=5
    	
    	double yL = Robot.oi.xboxJoy.getRawAxis(1);
    	double yR = Robot.oi.xboxJoy.getRawAxis(5);
    	
    //**writes the value of the raw axis to the motors in the Drive Train Class/subsystem	
    	Robot.driveTrain.driveL(yL);
    	Robot.driveTrain.driveR(yR);
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    protected void end() {
    	Robot.driveTrain.stop();
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}
