// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc6071.BCCFRCROBOT.commands;
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.command.Command;

import org.usfirst.frc6071.BCCFRCROBOT.OI;
import org.usfirst.frc6071.BCCFRCROBOT.Robot;

/**
 *
 */
public class RaiseClaw extends Command {

    private final DigitalInput switchTop = OI.switchArmTop;
	
    public RaiseClaw() {

    
        requires(Robot.clawArm);
        
        setTimeout(0.4);


    }
    
    //**These are the autogenerated sections of code that allow for the students to place the code before the command, during the command, or after the command 

    // Called just before this Command runs the first time
    protected void initialize() {
    	
    		boolean switch1;
    		
    		switch1 = switchTop.get();

    		Robot.clawArm.raise(switch1);
    	
    	
    
  
    }
    

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	
    	
    	
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return isTimedOut();
        
    }

    // Called once after isFinished returns true
    protected void end() {
    	Robot.clawArm.stop();
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    	end();
    }
}
