// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc6071.BCCFRCROBOT.commands;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc6071.BCCFRCROBOT.Robot;

/**
 *
 */
public class StopLaunch extends Command {

   
    public StopLaunch() {

    	//** You will need to place the requires(Robot.Launcher) command here
    	requires(Robot.launcher);
    }

    //**These are the autogenerated sections of code that allow for the students to place the code before the command, during the command, or after the command 
    
    
    
    // Called just before this Command runs the first time
    protected void initialize() {


    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	
    	org.usfirst.frc6071.BCCFRCROBOT.subsystems.Launcher.stop();
   
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    protected void end() {
    	org.usfirst.frc6071.BCCFRCROBOT.subsystems.Launcher.realStop();
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}
