// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc6071.BCCFRCROBOT;

import org.usfirst.frc6071.BCCFRCROBOT.commands.*;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.buttons.*;
import org.usfirst.frc6071.BCCFRCROBOT.subsystems.*;


/**
 * This class is the glue that binds the controls on the physical operator
 * interface to the commands and command groups that allow control of the robot.
 */
public class OI {
    //// CREATING BUTTONS
    // One type of button is a joystick button which is any button on a joystick.
    // You create one by telling it which joystick it's on and which button
    // number it is.
    // Joystick stick = new Joystick(port);
    // Button button = new JoystickButton(stick, buttonNumber);

    // There are a few additional built in buttons you can use. Additionally,
    // by subclassing Button you can create custom triggers and bind those to
    // commands the same as any other Button.

    //// TRIGGERING COMMANDS WITH BUTTONS
    // Once you have a button, it's trivial to bind it to a button in one of
    // three ways:

    // Start the command when the button is pressed and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenPressed(new ExampleCommand());

    // Run the command while the button is being held down and interrupt it once
    // the button is released.
    // button.whileHeld(new ExampleCommand());

    // Start the command when the button is released  and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenReleased(new ExampleCommand());


	public int halfSpped = 1;
	
    public JoystickButton clawLower;
    public JoystickButton clawRaise;
    public JoystickButton clawClose;
    public JoystickButton clawOpen;
    public JoystickButton launcherStart;
    public JoystickButton launcherStop;
    public JoystickButton joystickButton1;
    public JoystickButton joystickButton2;
    // public JoystickButton speedHalf;
    public Joystick xboxJoy;
    public static DigitalInput switchArmTop;
    public JoystickButton climbUp;
    public JoystickButton climbDown;
    

   

    public OI() {
       
//** This is where the input from the operator interface is declared, joystickbutton1 and joystickbutton2 can be either ignored or deleted as they are not used, but 
//** It may be helpful to leave these in at the moment for future assignment
        xboxJoy = new Joystick(0);
        
        switchArmTop = new DigitalInput(0);
        

        clawOpen = new JoystickButton(xboxJoy, 4);
        clawOpen.whileHeld(new OpenClaw());
        clawClose = new JoystickButton(xboxJoy, 3);
        clawClose.whileHeld(new CloseClaw());
        // Raise claw originally 2
        clawRaise = new JoystickButton(xboxJoy, 2);
        clawRaise.whileHeld(new RaiseClaw());
        // Low claw originally 1
        clawLower = new JoystickButton(xboxJoy,1);
        clawLower.whileHeld(new LowClaw() );
        // speedHalf = new JoystickButton(xboxJoy, 7);
        // speedHalf.whileHeld(new HalfSpeed());
        //climbDown = new  JoystickButton(xboxJoy, 6);
        //climbDown.whileHeld(new climbDown());
        climbUp = new JoystickButton(xboxJoy, 5);
        climbUp.whileHeld(new StartLaunch());

        
        
        

        // SmartDashboard Buttons
        SmartDashboard.putData("LowClaw", new LowClaw());
        SmartDashboard.putData("RaiseClaw", new RaiseClaw());
        SmartDashboard.putData("Close Claw", new CloseClaw());
        SmartDashboard.putData("Open Claw", new OpenClaw());
        SmartDashboard.putData("Start Launch", new StartLaunch());
        SmartDashboard.putData("Stop Launch", new StopLaunch());
        SmartDashboard.putData("Autonomous Command", new AutonomousCommand());
        SmartDashboard.putData("Joystick Values", new JoystickValues());
        SmartDashboard.putData("Expand Claw", new ExpandClaw());
        SmartDashboard.putData("ClimbUp", new climbUp());
        SmartDashboard.putData("ClimbDown", new climbDown());
    }

   
    public Joystick getXboxJoy() {
        return xboxJoy;
    }


   
}

