// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc6071.BCCFRCROBOT.subsystems;

import org.usfirst.frc6071.BCCFRCROBOT.RobotMap;
import org.usfirst.frc6071.BCCFRCROBOT.commands.*;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Talon;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class ClawGrip extends Subsystem {

    
    private final SpeedController gripMotor = RobotMap.clawGripGripMotor;

 
    public void initDefaultCommand() {
     
    }
    
   public void close() {
	   gripMotor.set(-1);
	   
   }
   public void open() {
	   gripMotor.set(1);
	   
   }
   
   public void expand() {
	   gripMotor.set(0.1);
	   
   }
   
   public void stop() {
	   gripMotor.set(0);
	   
   }
}
