// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc6071.BCCFRCROBOT.subsystems;

import org.usfirst.frc6071.BCCFRCROBOT.OI;
import org.usfirst.frc6071.BCCFRCROBOT.RobotMap;
import org.usfirst.frc6071.BCCFRCROBOT.commands.*;

import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Victor;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class ClawArm extends Subsystem {

   
    private final SpeedController clawMotor = RobotMap.clawArmClawMotor;
    private final DigitalInput switchTop = OI.switchArmTop;
    
    private boolean switchInput;
    
                                                         
    public void initDefaultCommand() {
      


    }
    
   public void raise(boolean switchInput) {
	   
	   //switchInput = true;
	   //switchInput = switchTop.get();
	   
	   //if (switchInput =! true) {
	   clawMotor.set(-0.8);
	   //}
	   
   }
   
   public void lower() {
	   clawMotor.set(0.8);
	   
   }
   
   public void stop() {
	   clawMotor.set(0);
   }
}

